development:
  adapter: postgresql
  database: prelaunchr_development
  host: localhost
test:
  adapter: postgresql
  database: prelaunchr_test
production:
  adapter: postgresql
  database: prelaunchr_development
  host: localhost
